INSERT INTO car (
  model,
  manufacturing_year,
  manufacturer,
  external_color,
  internal_color,
  vin,
  status,
  optional_items,
  category,
  kilometers,
  is_new,
  propulsion_type,
  listed_value,
  image_key
) VALUES
  (
    'Corolla XEi',
    2024,
    'Toyota',
    'Platinum White',
    'Black',
    '9BRBL3HE7R1234567',
    'AVAILABLE',
    '["Blind Spot Monitor","Adaptive Cruise Control","Apple CarPlay"]'::jsonb,
    'SEDAN',
    0.00,
    true,
    'COMBUSTION',
    162990.00,
    NULL
  ),
  (
    'T-Cross Comfortline',
    2023,
    'Volkswagen',
    'Silver',
    'Black',
    '9BWZZZ377VT765432',
    'AVAILABLE',
    '["Digital Cockpit","Reverse Camera","Front Sensors"]'::jsonb,
    'SUV',
    18450.00,
    false,
    'COMBUSTION',
    129900.00,
    NULL
  ),
  (
    'Onix LT',
    2022,
    'Chevrolet',
    'Blue',
    'Gray',
    '9BGKS48B0NG123456',
    'AVAILABLE',
    '["Multimedia 8in","Rear Parking Sensor"]'::jsonb,
    'HATCH',
    32600.00,
    false,
    'COMBUSTION',
    81900.00,
    NULL
  ),
  (
    'Ranger XLT',
    2024,
    'Ford',
    'Graphite Gray',
    'Black',
    '8AFAR23L6RJ123456',
    'AVAILABLE',
    '["4x4","Tow Hook","Lane Keep Assist"]'::jsonb,
    'PICKUP',
    0.00,
    true,
    'COMBUSTION',
    289000.00,
    NULL
  ),
  (
    'Dolphin Plus',
    2025,
    'BYD',
    'White',
    'Black',
    'LGXCE4CB2S1234567',
    'AVAILABLE',
    '["Heat Pump","360 Camera","Panoramic Roof"]'::jsonb,
    'HATCH',
    0.00,
    true,
    'ELECTRIC',
    184800.00,
    NULL
  )
ON CONFLICT (vin) DO NOTHING;
